rigid_body_config:
 ros__parameters:
  i_xx: 0.029125          # [kg*m^2]
  i_yy: 0.029125          # [kg*m^2]
  i_zz: 0.055225          # [kg*m^2]
  i_xy: 0.0               # [kg*m^2] 
  i_xz: 0.0               # [kg*m^2]
  i_yz: 0.0               # [kg*m^2] 
  m: 1.5                  # [kg]
  