px4_offboard:
 ros__parameters:
  p1_x: 0.0  # x position [m] of point 1, NED
  p1_y: 0.0  # y position [m] of point 1, NED
  p1_z: -5.0 # z position [m] of point 1, NED

  p2_x: 10.0 # x position [m] of point 2, NED
  p2_y: 0.0  # y position [m] of point 2, NED
  p2_z: -5.0 # z position [m] of point 2, NED

  p3_x: 10.0 # x position [m] of point 3, NED
  p3_y: 10.0 # y position [m] of point 3, NED
  p3_z: -5.0 # z position [m] of point 3, NED

  p4_x: 0.0  # x position [m] of point 4, NED
  p4_y: 10.0 # y position [m] of point 4, NED
  p4_z: -5.0 # z position [m] of point 4, NED

  repeats: 5 # number of repeats

  tolerance: 1.0 # [m]

  timer_period: 0.02 # [sec] offboard timer 