world:
 ros__parameters:
  windVelocityMean: 4.0
  windVelocityMax: 20.0
  windVelocityVariance: 0
  windDirectionMean: [1, 1, 0]
  windDirectionVariance: 0
  windGustStart: 0
  windGustDuration: 0
  windGustVelocityMean: 5.0
  windGustVelocityMax: 20.0
  windGustVelocityVariance: 0
  windGustDirectionMean: [1, 0, 0]
  windGustDirectionVariance: 0


             
