px4_config:
 ros__parameters: 
  MC_PITCHRATE_D: 0.005 # pitch rate d
  MC_PITCHRATE_I: 0.15 # pitch rate i
  MC_PITCHRATE_K: 1.0 # pitch rate k
  MC_PITCHRATE_P: 0.1 # pitch rate p
  MC_PITCH_P: 6.5 # pitch p

  MC_ROLLRATE_D: 0.005 # roll rate d
  MC_ROLLRATE_I: 0.15 # roll rate i
  MC_ROLLRATE_K: 1.0 # roll rate k
  MC_ROLLRATE_P: 0.1 # roll rate p
  MC_ROLL_P: 6.5 # roll p