px4_config:
 ros__parameters: 
  MC_PITCHRATE_D: 0.005
  MC_PITCHRATE_I: 0.15
  MC_PITCHRATE_K: 1.0
  MC_PITCHRATE_P: 0.1
  MC_PITCH_P: 6.5

  MC_ROLLRATE_D: 0.005
  MC_ROLLRATE_I: 0.15 
  MC_ROLLRATE_K: 1.0 
  MC_ROLLRATE_P: 0.1 
  MC_ROLL_P: 6.5